DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS application;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE auth_codes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  exp TIMESTAMP NOT NULL,
  client_id TEXT UNIQUE NOT NULL,
  redirect_uri TEXT UNIQUE NOT NULL
);
