DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS auth_codes;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS applications;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE auth_codes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  authorization_code BLOB NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  exp REAL NOT NULL,
  client_id TEXT NOT NULL,
  redirect_uri TEXT NOT NULL
);

CREATE TABLE clients (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  client_id TEXT NOT NULL,
  redirect_uri TEXT NOT NULL
);

CREATE TABLE applications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  client_id TEXT NOT NULL,
  redirect_uri TEXT NOT NULL,
  client_secret TEXT NOT NULL
);